services:
  - type: web
    name: free-sewaa
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_NAME
        value: freesewaa
      - key: FIREBASE_PROJECT_ID
        value: freesewaa-c8a41
      - key: MONGODB_URI
        sync: false
      - key: FIREBASE_API_KEY
        value: AIzaSyCvyZutFOJCjUlWZSxK11BTMgve5nk3dpE
      - key: FIREBASE_AUTH_DOMAIN
        value: freesewaa-c8a41.firebaseapp.com
      - key: FIREBASE_STORAGE_BUCKET
        value: freesewaa-c8a41.firebasestorage.app
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "325251516727"
      - key: FIREBASE_APP_ID
        value: 1:325251516727:web:65379ef1d78f615531f2b2
      - key: FIREBASE_MEASUREMENT_ID
        value: G-8Y2L714510
      - key: SUPER_ADMIN_EMAILS
        sync: false
